version: '3.0'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.0
    networks:
      - es-net   
    ports:
      - 9500:9500
      - 5000:5000
    volumes:
      - type: bind
        source: ./log/
        target: /usr/share/logstash/pipeline
        read_only: true
networks:
  es-net:
    driver: bridge